### ISSUE TITLE
Cannot match regex if the citekey contains ":" which is translated into "_" by obsidian

### ISSUE THREAD

**Issue by quarkquartet** [daeh/zotero-markdb-connect#121]
I'm using obsidian citation plugin to create note.

Sometimes my citekey contains ":". For example, let's say there is a paper whose citekey is `name:key`.

Then the obsidian note title is `@name_key`.

I set the regex as ^@[a-zA-Z0-9]+_[a-zA-Z0-9]+\.md$, or ^@.+_.+\.md$, or ^@.+[.:_].+\.md$, but none of them works.

Just wondering what should I write?

**Comment by daeh** [comment]
Check out the [readme](https://github.com/daeh/zotero-markdb-connect?tab=readme-ov-file#option-1-using-betterbibtex-citekeys) BetterBibTeX configuration details.

> - If your BetterBibTeX citekeys contain certain special characters (e.g. `:`, `/`), you will need to extract the citekeys from the markdown file's contents rather than its filename.

The `Default Filer Filter` should work (it's `^@(\S+).*\.md$`), and then you need to extract the BetterBibTeX citekey from the metadata. You can set the YAML metadata keyword in the `BetterBibTeX citekey - taken from YAML metadata` setting.

**Comment by quarkquartet** [comment]
Thank you that works.
