### ISSUE TITLE
Linking Notes without @

### ISSUE THREAD

**Issue by websurfer93** [daeh/zotero-markdb-connect#137]
I noticed that my notes are not prefixed with "@". How can I link them using just the citekey if they lack the "@"? I tried using the `.+.md$` code but could not locate anything. Please advise.

**Comment by websurfer93** [comment]
I just used RegExp `(\S+).*.md$` and it worked successfully.

**Comment by daeh** [comment]
yeah, exactly. That looks like almost the right file filter. In yours, the period in `.md` is matching any character and this will also match files that begin with a white space. It would only fail in edge cases that you're not likely to ever encounter, but a more robust pattern is `/`  `^(\S+).*\.md$`  `/i`.
