### ISSUE TITLE
Support Zettlr as MD editor

### ISSUE THREAD

**Issue by daeh** [daeh/zotero-markdb-connect#15]
related to #7

**Comment by daeh** [comment]
@halloichbingunnar will you take https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.18a/ZotObsCite-0.0.18a.xpi for a test drive and let me know if the advanced option to open notes in the system's default editor integrates with Zettlr in the ways that you want it to?

hopefully supports #7

**Comment by halloichbingunnar** [comment]
sure! just installed it, works perfectly fine - thank you very much! :)

**Comment by daeh** [comment]
closed by 0c176e7b7b236c719f3fa1e3839b28e7cd5e8030
