### ISSUE TITLE
Support logseq as MD editor

### ISSUE THREAD

**Issue by daeh** [daeh/zotero-markdb-connect#16]
open logseq issue for global URI: https://github.com/logseq/logseq/issues/2890#issuecomment-939699032

related forum post: https://discuss.logseq.com/t/deep-linking-or-url-scheme-allow-linking-to-logseq-pages-from-outside-the-app/3146/20

original request for ZotObsCite support: https://twitter.com/DavidJaggi/status/1484130826635853825

**Comment by davidjaggi** [comment]
It's now possible to open Logseq pages via URI. So this enhancement should be possible to implement.
https://github.com/logseq/logseq/releases/tag/0.6.6

**Comment by davidjaggi** [comment]
So the settings would be similar to the ones for Obsidian. All of the Zotero imports into Logseq start with an @ which is the default setting. This is the Logseq URL for my reference in the knowledge graph with the logseq://graph/knowledge?page=%40declercqMultilabelClassificationInteractive2019.

**Comment by daeh** [comment]
@davidjaggi will you take https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.18a/ZotObsCite-0.0.18a.xpi for a test drive and let me know how it works for you?

**Comment by daeh** [comment]
also @keQsia

**Comment by keQsia** [comment]
> also @keQsia

Are you sure it works for logseq? It looks weird.
![图片](https://user-images.githubusercontent.com/60851379/172037741-7c12c218-e4ec-4881-8108-d9bc369ea854.png)

**Comment by davidjaggi** [comment]
@daeh The plugin works nicely for me. I can open all my linked items in Logseq.
