### ISSUE TITLE
matching via filename (without @) does not work for me

### ISSUE THREAD

**Issue by fruchtblase** [daeh/zotero-markdb-connect#26]
Dear @daeh, 

for some reason the plugin won't work for me. The correct md files get picked up by the regex, and the corresponding citekeys are given to the plugin by bbt, but the don't get matched.
Am I doing something wrong or is this a bug?

[MarkDBConnect-debug.txt](https://github.com/daeh/zotero-markdb-connect/files/9179715/MarkDBConnect-debug.txt)

Kind regards 
fruchtblase

**Comment by daeh** [comment]
hi @fruchtblase you have configuration issues. First off, the file filter you're using, `\d{4}.md`, is not doing what you think it's doing. Try using:

`^.+\d{4}\.md`

That alone might resolve your issues.

(But if it doesn't, please upload one of your MD notes and I'll give you advice on how to match the BBT citekeys)

**Comment by fruchtblase** [comment]
thanks for the quick reply! 
looks like I misunderstood the readme, i thought that it is possible match on filenames (sans @)  without relying on metadata.

**Comment by daeh** [comment]
I understand how the readme could lead to that confusion. 

But yeah, when you use a custom file filter, the BBT citekey will need to come from the metadata. Let me know if that doesn't resolve the issue.

**Comment by tim-hilde** [comment]
Would love to see this issue resolved as using non-unicode character like `@` in filenames may lead to issues

**Comment by tim-hilde** [comment]
The Alfred workflow [Supercharged Citation Picker](https://github.com/chrisgrieser/alfred-bibtex-citation-picker) by pseudometa also shows if there is a markdown literature note corresponding to an entry: https://github.com/chrisgrieser/alfred-bibtex-citation-picker#literature-note-actions. Maybe this helps to implement it into this plugin. 

Sorry for cross posting, wasn't sure where it fits best

**Comment by daeh** [comment]
Hi @tim-hilde — I'm not sure I understand the issue that you're trying to resolve. Can you explain your use case?

I left this issue open for the OP to report back if getting the citekey from the metadata resolved their issue. 

Are you saying that you want the ability to match notes based on filenames and not [yaml front matter](https://help.obsidian.md/Advanced+topics/YAML+front+matter)? If so, can you tell me why specifying the citekey in a note's metadata isn't a solution for you?

Implementing file-name based citekey extraction with a user-defined regex expression isn't hard to implement. I just haven't seen a use case that warrants the extra complexity it would add to the plugin configuration. But I'm open to it if you can help me understand why it's necessary.

**Comment by tim-hilde** [comment]
Sorry if I didn't make myself clear enough. My use case is that I have markdown files that have just the citekey as a name. Without the `@` that is needed for the matching via filename. 

Sure, I could add the citekey to the front matter of all my hundreds of notes, but I don't see a strong reason to do that if there would be a rather easy way to stick to my workflow.

**Comment by ASchanke** [comment]
If putting the citekey in metadata, can the file title be anything?

**Comment by daeh** [comment]
@ASchanke if the citekey comes from the metadata, the file name is quite flexible. The markdown database application and file system imposes naming constraints, but this plugin should not.

**Comment by daeh** [comment]
closed by 3fff8d34f7ff00e0a18d7bff8c099892fcba9f8f
