### ISSUE TITLE
require citekey from frontmatter when using custom file filter

### ISSUE THREAD

**Issue by daeh** [daeh/zotero-markdb-connect#27]
re #26

**Comment by tim-hilde** [comment]
The Alfred workflow [Supercharged Citation Picker](https://github.com/chrisgrieser/alfred-bibtex-citation-picker) by pseudometa also shows if there is a markdown literature note corresponding to an entry: https://github.com/chrisgrieser/alfred-bibtex-citation-picker#literature-note-actions. Maybe this helps to implement it into this plugin

**Comment by daeh** [comment]
closed by e86346386883b3d682fe8b77b0c394f89dbb2cdf
