### ISSUE TITLE
zotero scanvault unable to parse 2 of 3 notes, which takes a long time to vanish

### ISSUE THREAD

**Issue by ghweili** [daeh/zotero-markdb-connect#28]
Then the following popups:

![image](https://user-images.githubusercontent.com/33361275/187014835-297587bc-55e1-4dd0-bf50-f277066185c1.png)

This process takes a while, like 20-30 seconds or more, I guess, during which zotero freezes.  Not sure if the freezing behavior can be eliminated.

 I'm using the current settings:

![image](https://user-images.githubusercontent.com/33361275/187014889-698f150b-eb76-462e-97d2-7f449c7e629b.png)

**Comment by daeh** [comment]
If you upload a debug report (the Advanced tab in prefs, "generate debugging file") and one of the md files you're trying to match, I can take a look. (None of the markdb-connect processes should be taking more than a few seconds)

**Comment by ghweili** [comment]
The md notes was created by bibnotes formatter; moreover, I didn't keep the citekey in the note title, but only in the yaml.

After chekcing the files generated in Tools/..Sync Tags, I notice that, this problem occurs when the abdminton template of bibnotes formatter is used, for which I can't keep the citekey info in the yaml. After using a customized template with yaml, the problem should be avoided.

The freezing behavior may be due to the fact that my computer is kind of slow recently.

**Comment by ghweili** [comment]
after more tests, I notice that zotero still freezes during its start:  firstly, the popups related to better bibtex would appear, during which I can still opearte zotero, then, after this popup disappears, and if I click somewhere on zotero, it becomes freeze, and when it recovers, the following popup appear.
![image](https://user-images.githubusercontent.com/33361275/187051749-0b305e4e-ceb2-40c4-8d57-ebd9701bfbb6.png)

Could it be possible that I use a title formats that does not include "@", making it searches for too many notes, though I have only several md notes there. 

Can markdb-connnect cause the zotero freeze? If so, could it be made to avoid this behavior, so that we can do other operations when it does is initialization?
