### ISSUE TITLE
Removes tags of files not found

### ISSUE THREAD

**Issue by jakepog** [daeh/zotero-markdb-connect#31]
I have to use two separate Obsidian vaults (work and personal) but one Zotero Library (one account). The issue is that tags are removed from Zotero items when Obsidian Vault files are not found, which occurs when I switch between work and personal Vaults. This seems reasonable behavior to clean up tags, but of course causes problems across multiple vaults. 

Perhaps a workaround could be, 1) option for tags be not removed at all, and/or 2) tags searched for items only in specific collections.

**Comment by daeh** [comment]
Hi @jakepog -- can you help me understand this use case? Will you describe what your setup for 2 vaults and one library is? 

It sounds like switching about your usecase means that either the path that MarkDBConnect is searching for MD files changes, or the location of the MD files changes? Is that true?

It's possible to have, on one computer, 2 Obsidian vaults and 1 Zotero library, where the tags are not removed when you switch vaults. It just requires that MarkDBConnect path and the location of the MD files don't change.

**Comment by daeh** [comment]
Hi @jakepog -- can you help me understand this use case? Will you describe what your setup? 

It's possible to have 2 Obsidian vaults and 1 Zotero library, where the MarkDBConnect tags are not removed when you switch vaults. It just requires that the path to the MD files in MarkDBConnect's settings doesn't change, and that the location of the MD files doesn't change. 

It sounds like switching vaults leads to a change, either in the path that MarkDBConnect searches for MD files, or in the location of the MD files. Is that true?

**Comment by jakepog** [comment]
Setup is one Zotero library, two Obsidian libraries, and two computer user accounts (work and personal). Each user account has one Obsidian vault and the shared Zotero library (via sync). 

Yes, switching between vaults/user accounts causes changes to MarkDBConnect Zotero tags according to which Obsidian library is available. The file paths also change, as the vaults are located in different user name folders and vault names, and have different vault search paths (different vault structure). I suppose I could organise the vaults so that their file structure is similar.

**Comment by daeh** [comment]
@jakepog please try https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.21 and see it works for you. In the advanced preferences, there's an option to turn off the remove-tag behavior.

![CleanShot 2023-01-14 at 20 10 54](https://user-images.githubusercontent.com/12652166/212504002-ada9ca78-f71d-489e-bde0-f410fbcd3e75.png)

addressed by 3fff8d34f7ff00e0a18d7bff8c099892fcba9f8f

**Comment by jakepog** [comment]
> hi @jakepog — Was this issue resolved by the release (0.0.22 or above)? Please let me know either way. I'll close the issue if I don't hear from you.

Apologies, didn't see notifications. Yes, brief testing in both libraries appears to show that no item tags are removed with remove-tag option selected. Many thanks to adding this behavior! Bit of a work around, but it will do.

**Comment by alacmo** [comment]
Hello, 

I am using Zotero 7.0.27 in a Debian 12 OS, and the plugin version used is: v0.1.8. 

I have a question regarding this feature: I have successfully configured the plugin so that it detects on my metadata the BibTex citekey. The setup regarding syncing the markdown items is as follows:

<img width="799" height="623" alt="Image" src="https://github.com/user-attachments/assets/12b5836a-691c-46be-8cce-11fbe8623a61" />


However, when I remove from obsidian all markdown files referenced to an article, the tag is not being removed. Is there maybe any missing setup element?

Thank you so much for your support.
