### ISSUE TITLE
Support matching via filename without @

### ISSUE THREAD

**Issue by tim-hilde** [daeh/zotero-markdb-connect#33]
Currently, matching via filename requires either `@` at the beginning of the file or the citekey present in the yaml frontmatter. I'd like to match via filenames without `@` and without a specific yaml frontmatter. Just via a filename in this format: `citekey.md`

**Comment by daeh** [comment]
Will be in the next release. I have a ton of January deadlines, but this feature is on the way.

dup #26, related #27

**Comment by daeh** [comment]
@tim-hilde please try https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.21 and let me know if it works for you. Use the Custom File Filter regex to specify a file filter with a capturing group. If the filename is simply the citekey, you could use: `^(.+)\.md$`.

**Comment by tim-hilde** [comment]
Yes, that seems to do the trick. Thanks!

**Comment by daeh** [comment]
closed by 3fff8d34f7ff00e0a18d7bff8c099892fcba9f8f
