### ISSUE TITLE
Parsing Errors With LogSeq

### ISSUE THREAD

**Issue by mruderman** [daeh/zotero-markdb-connect#34]
I'm having a similar issue as:
https://discuss.logseq.com/t/my-zotero-logseq-zettlr-word-workflow/8900/17?u=flan
Also, under Linux.

## Here is an example Zotero item:
![image](https://user-images.githubusercontent.com/63901943/212038948-961e463e-19fd-4bc3-ab1b-e9e40f1d03ee.png)

## Here are my "Locating  MD Files" settings:
![image](https://user-images.githubusercontent.com/63901943/212038415-494ceec0-30b1-4821-9ac9-78d7061ac56d.png)

## This is what the LogSeq YAML looks like:
![image](https://user-images.githubusercontent.com/63901943/212039492-e1a49b4d-88e0-4789-b388-2ab6e37b9612.png)

## Here is an example of a parsing error I get:
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "zt-zhangBayesianMixedHidden2014",
  "path": "/home/onomat/GitProjects/FlogSeq3/pages/zt-zhangBayesianMixedHidden2014.md"
 },

I'm not technical enough to find the parsing error very informative.

Thank you for developing this plugin. I'd appreciate any insight you might have.

**Comment by daeh** [comment]
Hi @mruderman -- Try using this regex pattern instead:

```
^zt-(.+)\.md$
```

Make sure you've upgraded to https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.21

**Comment by mruderman** [comment]
@daeh Thanks for your reply. I think the XPI is missing from https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.21
I forgot what modifications need to happen in the zip before changing the extension to xpi. Thanks again.

**Comment by daeh** [comment]
THANK YOU @mruderman ! Goodness, I don't know how that got by me. It's updated now.

**Comment by daeh** [comment]
(Note the string you enter should just be `^zt-(.+)\.md$`, not `/^zt-(.+)\.md$/i`)

**Comment by mruderman** [comment]
Apologies for the delayed response...it's working! This plugin is a lifesaver for me, thank you for developing it!

**Comment by daeh** [comment]
Great. Thanks for the update!

closed by 52ad81a18310b5695c9ad5933fea7861b29342de
