### ISSUE TITLE
0 matches after upgrade to 0.0.21

### ISSUE THREAD

**Issue by glocalglocal** [daeh/zotero-markdb-connect#36]
I just updated MarkDBConnect to 0.0.21 (and BBT to 6.7.50) and every time I start MarkDBConnect reports all cited entries fail to be matched. Obsidian and BBT still work as expected. The only thing that is not working is that the MarkDBConnect option on the context menu does not show for items that are actually cited in Obsidian. 

Looking at the `MarkDBConnect-missing-entries.json` it all looks fine to me. Here is the first of hundreds of entries: 

` {`
`  "citekey": "allenInformationFlowResearch1969.md",`
`  "citekey_metadata": null,`
`  "citekey_title": "allenInformationFlowResearch1969.md",`
`  "zotkeys": [],`
`  "zotids": [],`
`  "name": "@allenInformationFlowResearch1969",`
`  "path": "path_to_file\\@allenInformationFlowResearch1969.md"`
` }`

I created a couple of new citations in Obsidian, including one of a new entry in Zotero. MarkDBConnect reports these as additional ones that it fails to match and does not set the citation tag in Zotero.

**Comment by daeh** [comment]
Hi @glocalglocal -- thanks very much for reporting this, and for including the log. Please try https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.22 and let me know if that resolves the issue for you or not.

**Comment by glocalglocal** [comment]
Wow! That was fast and worked. Thanks!

**Comment by daeh** [comment]
appreciate you reporting the issue. cheers

closed by 52ad81a18310b5695c9ad5933fea7861b29342de
