### ISSUE TITLE
how to close this window?

### ISSUE THREAD

**Issue by xiaozhe2333** [daeh/zotero-markdb-connect#37]
I'm not sure whether this window is caused by this plug-in, but I still want to ask how to close this window
![image](https://user-images.githubusercontent.com/92240019/216548362-d3172473-268f-44fc-a871-8509d3f95f28.png)

**Comment by daeh** [comment]
I've not seen the graph view from obsidian show up in zotero before. Did you figure out what's causing it?

**Comment by xiaozhe2333** [comment]
I have found that it was caused by another plug-in：zotero tag

**Comment by daeh** [comment]
thanks for letting me know!
