### ISSUE TITLE
Invalid tag name, containing an "/"

### ISSUE THREAD

**Issue by jankap** [daeh/zotero-markdb-connect#38]
I'd love to use a `status/HasMdNotes` tag, but the plugin seems not to accept custom tags containing a slash. Can this be fixed?

Thanks :)

**Comment by daeh** [comment]
it shouldn't cause an issues to allow `/` characters in the tag string. This should be in the next release.

**Comment by daeh** [comment]
@jankap Let me know of https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.24 resolves this or not

**Comment by jankap** [comment]
Nice, will do so tomorrow.

**Comment by daeh** [comment]
fyi I'm going to close this issue as complete in about a week, but feel free to reopen if this issue is unresolved @jankap

**Comment by jankap** [comment]
Yes, it works. Thanks!
