### ISSUE TITLE
MarkDB does not recognize YAML citekey enclosed in quotation marks

### ISSUE THREAD

**Issue by dbobak** [daeh/zotero-markdb-connect#39]
Citekeys in YAML frontmatter enclosed in quotation marks are not recognised. For example:

```
citekey: "somecitekey"
citekey: 'othercitekey'
```

Both of them are not recognized as correct citekeys, but they should - quoting strings in YAML is allowed.

**Comment by daeh** [comment]
Makes sense to address this. 

The other constraints on citekeys probably make quoting them in the yaml unnecessary, but I agree that the plugin should be able to parse quoted values.

Should be in next release.

**Comment by daeh** [comment]
fyi I'm going to close this issue as complete in about a week, but feel free to reopen if this issue is unresolved @dbobak

**Comment by dbobak** [comment]
@daeh, sorry for the delay.  Now everything is perfect, the quotation marks are parsed correctly. Thank you!

**Comment by daeh** [comment]
Thanks for reporting back!
