### ISSUE TITLE
MarkDB does not recognize YAML citekey

### ISSUE THREAD

**Issue by Kiss-World** [daeh/zotero-markdb-connect#41]
My naming rule is `.+\.md$ `,and to put the citekey in the yaml area. But when the file name does not contain @citekey, it cannot match correctly. I tested it many times and did not achieve it. So can this plugin rely only on the citekey configuration in the yaml area? I don’t know where the problem is.
![image](https://user-images.githubusercontent.com/44720566/226626081-6f1faa9a-7bbe-4e30-8ff4-cc6658436e59.png)
![image](https://user-images.githubusercontent.com/44720566/226626218-6b749727-60ce-401b-98d5-6ea28386f950.png)

**Comment by Kiss-World** [comment]
> 
[MarkDBConnect-debug.txt](https://github.com/daeh/zotero-markdb-connect/files/11035499/MarkDBConnect-debug.txt)
![image](https://user-images.githubusercontent.com/44720566/226782214-27d3ce3f-a971-48fd-8c1f-7b3223fca1c3.png)

**Comment by Kiss-World** [comment]
[@NaWaErBaoDian 纳瓦尔宝典.md](https://github.com/daeh/zotero-markdb-connect/files/11040619/%40NaWaErBaoDian.md)
@daeh

**Comment by daeh** [comment]
you have a newline before the first `---`. Markdown metadata needs to begin on the first line of the file.

See https://help.obsidian.md/Editing+and+formatting/Metadata for config requirements
> You can add metadata to your notes by adding a block on the first line of your note. The block must start and end with three hyphens (---).


![CleanShot 2023-03-22 at 08 57 27@2x](https://user-images.githubusercontent.com/12652166/226945515-ef73a1da-1746-43d4-99ef-6f6ce6384efd.png)
