### ISSUE TITLE
Support for multiple citekeys

### ISSUE THREAD

**Issue by emdoe** [daeh/zotero-markdb-connect#42]
Thanks for the great plugins! On my side, the plugin appears to be incompatible with more than one `citekey`. I wonder if it's a bug? Namely, suppose we have a file like

```md
---
citekey: [key1, key2, key3]
tags: [tag1, tag2, tag3]
---
content
```

On my computer the file `MarkDBConnect-debug.json` appears as:

```json
{
   "citekey": null,
   "citekey_metadata": null,
   "citekey_title": null,
   "zotkeys": [],
   "zotids": [],
   "name": "filename",
   "path": "/[path-to-vault]/[filename].md"
  },
```
And my config is

<img width="765" alt="image" src="https://user-images.githubusercontent.com/2088116/229620576-d3a1f8d4-2ff2-46c9-875b-41bad57fd857.png">

Besides, I also test 

```md
---
citekey: 
  - key1
  - key2
  - key3
---
content
```

Unfortunately, it doesn't seem to work as well.

I hope the above information is useful and thanks again for the great plugin!

**Comment by daeh** [comment]
Only one citekey per markdown file is supported. See readme, e.g.: 
> MarkDB-Connect will only link the markdown note to one BetterBibTeX-citekey

**Comment by emdoe** [comment]
Ah I see, thank you!
