### ISSUE TITLE
feature  request

### ISSUE THREAD

**Issue by qiuqianyuanluo** [daeh/zotero-markdb-connect#45]
Hi,
I am writing to request a new feature for your plugin. I would like to suggest adding support for the markdown files exported from Readwise, so that the plugin can associate and tag the Readwise reading records in Zotero items.
As you may know, many users of Zotero also use Readwise to manage their highlights and notes. It would be very convenient if the plugin could automatically recognize and link the Readwise markdown files to the corresponding Zotero items, and tag them with relevant keywords or labels.
The exported markdown files from Readwise usually follow a specific naming convention, such as "Article Title(highlights).md". It would be great if the plugin could recognize this convention and use it to identify the associated Zotero items.
I believe that adding this feature would greatly enhance the functionality of your plugin and benefit many users who use both Zotero and Readwise. Thank you for your consideration!

My best,
qqyl

**Comment by daeh** [comment]
I can take a look. Can you upload a example readwise markdown file?

**Comment by qiuqianyuanluo** [comment]
> I can take a look. Can you upload a example readwise markdown file? 我可以看一下。你能上传一个示例读取标记文件吗？

Thank you very much for your reply! I apologize for just seeing this message.

Great, here's a sample file from Readwise:
https://wormhole.app/dO2L3#FsED7D3G-b4V7Jcbq7dmQg

The "title" section matches the name of the paper grabbed by Zotero, and there shouldn't be any duplicates in general, so it could be used as an identifying marker.

Once again, I want to express my gratitude for this project!

**Comment by daeh** [comment]
Hi @qiuqianyuanluo I added more configuration options to the zotero 7 compatible version of this plugin. I can't access the file you linked any more, but I suspect it will work for your use case now.

So if this is still relevant, please give it another go with any version >= than `0.1.0-rc.1`.

https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0-rc.1

**Comment by daeh** [comment]
Closing as resolved. Feel free to reopen if v0.1.0 or later doesn't work for you.
