### ISSUE TITLE
Failed to configure RegEx

### ISSUE THREAD

**Issue by NickoJow** [daeh/zotero-markdb-connect#46]
Hey, I tried to write the RegEx to macht md notes according to the Zotero-Item-Key just as suggested in the parantheses from the picture below. But the line failed to matching md notes with Zotero items. 

![image](https://github.com/daeh/zotero-markdb-connect/assets/53993771/52532d81-660d-406e-baee-e335c6a35100)

This is what I was trying to match in metadata (in Logseq)
![image](https://github.com/daeh/zotero-markdb-connect/assets/53993771/dde55a8f-4c0c-40d7-b883-a89f3de33332)

These are the lines that I tried:

- `(?!(zotero:\/\/select\/library\/items\/))(\w{8})`

- `(?<=zotero:\/\/select\/library\/items\/)(\w{8})` (the positive lookbehind feature was reported to be not supported, so I changed to the above one, but failed again)

Thanks in advance 🥺🥺🥺

**Comment by daeh** [comment]
Did you try something simple like `\[Local library\]\(zotero:\/\/select\/library\/items\/([a-zA-Z0-9]{8})\)`? The first capturing group (at index 1) is used as the ZoteroKey, so probably don't need a negative lookahead.

**Comment by daeh** [comment]
and fyi, you can always trouble shoot in the Zotero js console (Tools > Developer > Run JavaScript). E.g.

```
const contents = "library-catalog:: Open WorldCat \nlinks:: [Local library](zotero://select/library/items/EIM8TCL5), [Web library] (https://www.zotero.org/users/8949353/items/EIM8TCL5)\n"
const re_contents = /\[Local library\]\(zotero:\/\/select\/library\/items\/([a-zA-Z0-9]{8})\)/
contents.match(re_contents)[1]
```
returns
```
EIM8TCL5
```

**Comment by NickoJow** [comment]
It is working!!! Thanks for your helping hand!!! It's true that I need some more prectical expierence of RegEx.

Advice taken. Thx again 🌹🌹🌹
