### ISSUE TITLE
Add support for Zotero 7

### ISSUE THREAD

**Issue by Kullenej** [daeh/zotero-markdb-connect#48]
Please add support for Zotero 7. Thanks!

**Comment by daeh** [comment]
Zotero 7 will require fairly extensive rewrites of most plugins (see https://github.com/retorquere/zotero-better-bibtex/issues/2522). I'm going to hold off on redeveloping MarkDB-Connect until BetterBibTeX has a working beta since one of the major MDBC workflows relies on BBT citekeys.

**Comment by nhan000** [comment]
Hi, I don't mean to be pushy, but BetterBibTeX can now work with Zotero 7 quite well. The only remaining issue is the “citekey display/edit field awaits API from Zotero” https://github.com/retorquere/zotero-better-bibtex/issues/2522#issue-1720644883

**Comment by daeh** [comment]
It's in development. The new requirements for zotero 7 plugs require a ground-up rebuild, but I have some of the core components working. An additional complication is building a plugin that supports both zotero 6 and 7. But maybe I'll release a beta with exclusively zotero 7 compatibility before tackling that.

**Comment by nhan000** [comment]
Thanks for the update. I'd say to just release a beta plugin that work only with Zotero 7. I've seen a few developers rolling out updates that work with both Zotero 6 and Zotero 7, which causes some bug with Zotero 6, or they have to remove some features. Eventually most of them just drop Zotero 6 support, and people have to trace back what the stable release for Zotero 6 was and reinstall it.

I think as of now, those who choose to remain with Zotero 6 don't want anything that's buggy. Your plugin currently works very well with Zotero 6, so I think it's better to make a separate version for Zotero 7.

**Comment by daeh** [comment]
Quick update on Zot7 support - the core functionality issues are resolved. Main remaining task is getting the preference window situated.

**Comment by Kaergo** [comment]
Thank you and please get this done as soon as possible！

**Comment by kerim** [comment]
This is one of the few plugins I really depend on for my Logseq workflow. Any progress with the preference window? Thanks for your work!

**Comment by daeh** [comment]
yeah, everything is close. I'm hoping that I'll have time next week to connect that parts and get an alpha out.

**Comment by Kaergo** [comment]
hi daeh, how it is going?

**Comment by daeh** [comment]
early release candidate available here https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0-rc.0

**Comment by wklimowicz** [comment]
Just tested on mine, works perfectly on:
* Fedora 38
* Zotero 7.0.0-beta.52+2f8e536f2 (64-bit)
* zotero-markdb-connect 0.1.0-rc.0

**Comment by daeh** [comment]
@kerim The rc will be available again later today.

**Comment by daeh** [comment]
Here's `rc.1`. Please let me know how it works for you. 

https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0-rc.1

Since this plugin is fairly flexible and encompasses a variety of use-cases, feedback about what **is** working is very appreciated.

**Comment by kerim** [comment]
Great. Seems to be working as intended. Thanks!

**Comment by daeh** [comment]
fyi I found a typo that messed with the obsidian URI. It's fixed in `rc.2`

https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0-rc.2

**Comment by daeh** [comment]
If you installed a prerelease, you'll need to manually update to `v0.1.0-rc.6` (or later). I changed the addon ID and it won't autoupdate to a different ID than the installed version.

https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0-rc.6
