### ISSUE TITLE
markdb-connect won't add the required tag

### ISSUE THREAD

**Issue by docsez** [daeh/zotero-markdb-connect#50]
I've tried disabling/removing any other plugins, restarted both zotero and obsidian, looked at the debug logs.. [OSX Ventura, Zotero 6.0.29, Obsidian 1.4.16, MarkDBConnect 0.0.24]

When zotero starts it throws up:
[JavaScript Error: "TypeError: items is undefined" {file: "chrome://markdbconnect/content/scripts/mdbconnect.js" line: 782}]

When I try 'MarkDBConnect Sync Tags' the debug window show that it finds all the right .md files but doesn't add the tag to them?  Immediately after the list of files it finds, the window shows:
(4)(+0000022): SELECT COALESCE(IA.parentItemID, itemID) AS itemID FROM items LEFT JOIN itemAnnotations IA USING (itemID) WHERE (itemID NOT IN (SELECT itemID FROM deletedItems UNION SELECT itemID FROM itemNotes WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems) UNION SELECT itemID FROM itemAttachments WHERE parentItemID IS NOT NULL AND parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM deletedItems)UNION SELECT itemID FROM itemAnnotations WHERE parentItemID IN (SELECT itemID FROM itemAttachments WHERE parentItemID IN (SELECT itemID FROM deletedItems)))) AND (itemID IN (SELECT itemID FROM items WHERE libraryID=?)) [1]

... and there it stops.

Any advice?

**Comment by daeh** [comment]
The latest version of BetterBibTeX introduced a breaking change. It should be resolved in https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.25

Let me know if not

**Comment by docsez** [comment]
Works perfectly now, thank you!

**Comment by daeh** [comment]
closed by b91cc7ff7bc04675d3d707dac6246c05d291d7df
