### ISSUE TITLE
Obsidian links don't work since the last update.

### ISSUE THREAD

**Issue by DannyHatcher-Git** [daeh/zotero-markdb-connect#51]
I changed nothing but now my markdown files don't link with the zotero citekey.

No idea why not - my assumption is it is something to do with the update 🤷‍♂️

Citekey and filenames still match but the plugin doesn't recognize that.

**Comment by daeh** [comment]
I wonder if it's a BetterBibTeX version conflict. https://github.com/daeh/zotero-markdb-connect/issues/50#issuecomment-1778275962 . If that's all, it should be a relatively quick fix. Can you let me know what version of BetterBibTeX and MDConnect you're using? 

You can roll back a version until it's resolved https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.0.24

**Comment by DannyHatcher-Git** [comment]
I unistalled better bibtex and on reintalling there was an update. Odd it didn't do it automatically or show up but now everything is working 👍
