### ISSUE TITLE
add option to open note in default editor

### ISSUE THREAD

**Issue by daeh** [daeh/zotero-markdb-connect#7]
either as an option that dictates the contextual menu action or as another contextual menu item

**Comment by halloichbingunnar** [comment]
Thank you @daeh for your plugin! I love your idea how to better connect Zotero with a proper markdown editor/knowledge management. 

I am myself not using Obsidian but Zettlr – but the option "open in default editor" would enable opening the file directly in any markdown environment, as long as it is set as the standard app, right? 

(Right now I stick with "Show file" and then open the file manually in Zettlr)

**Comment by daeh** [comment]
Hi @halloichbingunnar — It's pretty easy to implement the 'open in default editor' function for MacOS, but it's much harder to do in a reliable cross-platform way. I could consider making the 'default editor' option available conditional on the OS. What OS are you on?

**Comment by halloichbingunnar** [comment]
I'm really sorry: I'm on windows... 😬

**Comment by daeh** [comment]
Support for opening MD files in the system's default editor added in the alpha release [v0.0.18a ZotObsCite-0.0.18a.xpi (download)](https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.18a/ZotObsCite-0.0.18a.xpi)

**Comment by daeh** [comment]
closed by 0c176e7b7b236c719f3fa1e3839b28e7cd5e8030
