### ISSUE TITLE
Allow "#" character in tag.

### ISSUE THREAD

**Issue by wklimowicz** [daeh/zotero-markdb-connect#93]
First of all, thank you for the great plugin!

I'm using this alongside [zotero-style](https://github.com/MuiseDestiny/zotero-style), which has a feature for tags that begin with the "#" character. This is disabled by default here: 

https://github.com/daeh/zotero-markdb-connect/blob/934ac019a1b4b1e34dcf0438d7ad70fd183c1350/src/modules/mdbcScan.ts#L2322

Simply removing that line seems to work fine -- is there a specific reason these characters are excluded? If not, can this be disabled?

**Comment by daeh** [comment]
Yeah, I can remove that constraint. Should have time to make a relase tomorrow.

**Comment by daeh** [comment]
See if [v0.1.0](https://github.com/daeh/zotero-markdb-connect/releases/tag/v0.1.0) works for you, @wklimowicz

**Comment by wklimowicz** [comment]
Works great, thank you!
